### ISSUE TITLE
Link to Rejection Wall Calculator on Stuff page says "Calclulator"

### ISSUE THREAD

**Issue by sqiouyilu** [HBBisenieks/rejection-wall#2]
What it says in the subject line.

<img width="485" alt="screen shot 2018-02-28 at 1 34 27 pm" src="https://user-images.githubusercontent.com/27913821/36814364-245bd388-1c8c-11e8-904b-26f4251310cb.png">

http://hilarybisenieks.com/stuff.html

**Comment by HBBisenieks** [comment]
Get u a friend who will proofread your website.

**Comment by sqiouyilu** [comment]
Verified ✅
